# NNDL Week 2

**Name: Shashank Goel**
**Roll no: J011**
**SAP ID: 70092300008**
**Batch: B.Tech Data Science**

In [1]:
import numpy as np

In [2]:
x = np.array([2.5, -1.5])  
print(x)
print(x.shape)

[ 2.5 -1.5]
(2,)


In [3]:
w = np.array([1.25, -1.5]) # One weight per input
b = 0.3

In [4]:
z =  np.dot(w, x) + b  # Score
z

np.float64(5.675)

In [5]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

a = sigmoid(z)
a

np.float64(0.9965810602741516)

In [6]:
zs = np.array([-2.0, -1.0, 0.0, 1.5, 2.0, 10.0, 20.0])
zs

array([-2. , -1. ,  0. ,  1.5,  2. , 10. , 20. ])

In [7]:
sigmoid(zs)

array([0.11920292, 0.26894142, 0.5       , 0.81757448, 0.88079708,
       0.9999546 , 1.        ])

In [8]:
np.tanh(zs)

array([-0.96402758, -0.76159416,  0.        ,  0.90514825,  0.96402758,
        1.        ,  1.        ])

In [9]:
np.maximum(0, zs)

array([ 0. ,  0. ,  0. ,  1.5,  2. , 10. , 20. ])

# 2 layers

In [10]:
x = np.array([1, 2])
W1 = np.array([[1.0, 1.5], [0.5, -1.0]])
W2 = np.array([[1.0, 1.5]])

In [11]:
h = W1 @ x
h

array([ 4. , -1.5])

In [12]:
out_two_layers = W2 @ h
out_two_layers

array([1.75])

In [13]:
W_combined = W2 @ W1
W_combined

array([[1.75, 0.  ]])

In [14]:
out_one_layer = W_combined @ x
out_one_layer

array([1.75])

In [15]:
h_best = np.maximum(0, W1 @ x)
h_best

array([4., 0.])

In [17]:
out_best = W2 @ h_best
out_best

array([4.])

### This ipynb is submitted by Shashank Goel